<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  
  <Target Name="CopyVictoryEngine" AfterTargets="Build">
	<Copy
		SourceFiles="$(SolutionDir)x64\Debug\VictoryEngine.dll"
		DestinationFolder="$(OutputPath)" 
	/>
	<Copy 
		SourceFiles="$(SolutionDir)x64\Debug\dxcompiler.dll"
		DestinationFolder="$(OutputPath)"
	/>
	<Copy
		SourceFiles="$(SolutionDir)x64\Debug\dxil.dll"
		DestinationFolder="$(OutputPath)"
	/>
  </Target>
  
</Project>
